/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

module uart_top(rst, data_in, wr_en, clk, rdy_clr, baud_sel, rdy, busy, data_out);
  input rst;
  wire rst;
  input [7:0] data_in;
  wire [7:0] data_in;
  input wr_en;
  wire wr_en;
  input clk;
  wire clk;
  input rdy_clr;
  wire rdy_clr;
  input [2:0] baud_sel;
  wire [2:0] baud_sel;
  output rdy;
  wire rdy;
  output busy;
  wire busy;
  output [7:0] data_out;
  wire [7:0] data_out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire rx_clk_en;
  wire tx_clk_en;
  wire tx_line;
  wire \u_baud.counter_rx[0] ;
  wire \u_baud.counter_rx[1] ;
  wire \u_baud.counter_rx[2] ;
  wire \u_baud.counter_rx[3] ;
  wire \u_baud.counter_rx[4] ;
  wire \u_baud.counter_rx[5] ;
  wire \u_baud.counter_rx[6] ;
  wire \u_baud.counter_rx[7] ;
  wire \u_baud.counter_rx[8] ;
  wire \u_baud.counter_rx[9] ;
  wire \u_baud.counter_tx[0] ;
  wire \u_baud.counter_tx[10] ;
  wire \u_baud.counter_tx[11] ;
  wire \u_baud.counter_tx[12] ;
  wire \u_baud.counter_tx[13] ;
  wire \u_baud.counter_tx[1] ;
  wire \u_baud.counter_tx[2] ;
  wire \u_baud.counter_tx[3] ;
  wire \u_baud.counter_tx[4] ;
  wire \u_baud.counter_tx[5] ;
  wire \u_baud.counter_tx[6] ;
  wire \u_baud.counter_tx[7] ;
  wire \u_baud.counter_tx[8] ;
  wire \u_baud.counter_tx[9] ;
  wire \u_baud.sel_q[0] ;
  wire \u_baud.sel_q[1] ;
  wire \u_baud.sel_q[2] ;
  wire \u_rx.index[0] ;
  wire \u_rx.index[1] ;
  wire \u_rx.index[2] ;
  wire \u_rx.index[3] ;
  wire \u_rx.rx_s ;
  wire \u_rx.rx_sync[0] ;
  wire \u_rx.sample[0] ;
  wire \u_rx.sample[1] ;
  wire \u_rx.sample[2] ;
  wire \u_rx.sample[3] ;
  wire \u_rx.state[0] ;
  wire \u_rx.state[1] ;
  wire \u_rx.state[2] ;
  wire \u_rx.temp[0] ;
  wire \u_rx.temp[1] ;
  wire \u_rx.temp[2] ;
  wire \u_rx.temp[3] ;
  wire \u_rx.temp[4] ;
  wire \u_rx.temp[5] ;
  wire \u_rx.temp[6] ;
  wire \u_rx.temp[7] ;
  wire \u_tx.bitpos[0] ;
  wire \u_tx.bitpos[1] ;
  wire \u_tx.bitpos[2] ;
  wire \u_tx.data[0] ;
  wire \u_tx.data[1] ;
  wire \u_tx.data[2] ;
  wire \u_tx.data[3] ;
  wire \u_tx.data[4] ;
  wire \u_tx.data[5] ;
  wire \u_tx.data[6] ;
  wire \u_tx.data[7] ;
  wire \u_tx.state[0] ;
  wire \u_tx.state[1] ;
  sky130_fd_sc_hd__clkinv_1 _279_ (
    .A(\u_tx.state[1] ),
    .Y(_070_)
  );
  sky130_fd_sc_hd__clkinv_1 _280_ (
    .A(\u_rx.state[2] ),
    .Y(_071_)
  );
  sky130_fd_sc_hd__clkinv_1 _281_ (
    .A(\u_baud.counter_rx[0] ),
    .Y(_072_)
  );
  sky130_fd_sc_hd__clkinv_1 _282_ (
    .A(\u_baud.counter_tx[6] ),
    .Y(_073_)
  );
  sky130_fd_sc_hd__clkinv_1 _283_ (
    .A(\u_baud.counter_rx[7] ),
    .Y(_074_)
  );
  sky130_fd_sc_hd__clkinv_1 _284_ (
    .A(rx_clk_en),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nor2_1 _285_ (
    .A(\u_tx.state[0] ),
    .B(\u_tx.state[1] ),
    .Y(_076_)
  );
  sky130_fd_sc_hd__clkinv_1 _286_ (
    .A(_076_),
    .Y(busy)
  );
  sky130_fd_sc_hd__nand3_1 _287_ (
    .A(\u_rx.sample[0] ),
    .B(\u_rx.sample[1] ),
    .C(\u_rx.sample[2] ),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand4_1 _288_ (
    .A(\u_rx.sample[0] ),
    .B(\u_rx.sample[1] ),
    .C(\u_rx.sample[2] ),
    .D(\u_rx.sample[3] ),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor2_1 _289_ (
    .A(_075_),
    .B(_078_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__clkinv_1 _290_ (
    .A(_079_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nor3_1 _291_ (
    .A(\u_rx.index[0] ),
    .B(\u_rx.index[1] ),
    .C(\u_rx.index[2] ),
    .Y(_081_)
  );
  sky130_fd_sc_hd__a31oi_1 _292_ (
    .A1(\u_rx.index[3] ),
    .A2(_079_),
    .A3(_081_),
    .B1(_071_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__a21oi_1 _293_ (
    .A1(\u_rx.state[0] ),
    .A2(_079_),
    .B1(_082_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nor2_1 _294_ (
    .A(rst),
    .B(_083_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor3_1 _295_ (
    .A(\u_rx.sample[0] ),
    .B(\u_rx.sample[1] ),
    .C(\u_rx.sample[2] ),
    .Y(_084_)
  );
  sky130_fd_sc_hd__and2_0 _296_ (
    .A(\u_rx.sample[3] ),
    .B(_084_),
    .X(_085_)
  );
  sky130_fd_sc_hd__nand2_1 _297_ (
    .A(rx_clk_en),
    .B(_085_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__and3_1 _298_ (
    .A(\u_rx.state[1] ),
    .B(rx_clk_en),
    .C(_085_),
    .X(_087_)
  );
  sky130_fd_sc_hd__nand3_1 _299_ (
    .A(\u_rx.state[1] ),
    .B(rx_clk_en),
    .C(_085_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__a21oi_1 _300_ (
    .A1(\u_rx.state[0] ),
    .A2(_080_),
    .B1(rst),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nand2_1 _301_ (
    .A(_088_),
    .B(_089_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand2_1 _302_ (
    .A(\u_rx.state[1] ),
    .B(_086_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand4_1 _303_ (
    .A(\u_rx.index[3] ),
    .B(\u_rx.state[2] ),
    .C(_079_),
    .D(_081_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a21oi_1 _304_ (
    .A1(_090_),
    .A2(_091_),
    .B1(rst),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2b_1 _305_ (
    .A_N(rdy_clr),
    .B(rdy),
    .Y(_092_)
  );
  sky130_fd_sc_hd__a21oi_1 _306_ (
    .A1(_088_),
    .A2(_092_),
    .B1(rst),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _307_ (
    .A(\u_rx.temp[7] ),
    .B(_087_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand2_1 _308_ (
    .A(data_out[7]),
    .B(_088_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__a21oi_1 _309_ (
    .A1(_093_),
    .A2(_094_),
    .B1(rst),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand3_1 _310_ (
    .A(\u_rx.rx_s ),
    .B(\u_rx.state[0] ),
    .C(_084_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nor2_1 _311_ (
    .A(\u_rx.sample[3] ),
    .B(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor2_1 _312_ (
    .A(_075_),
    .B(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__o21ai_0 _313_ (
    .A1(\u_rx.sample[3] ),
    .A2(_095_),
    .B1(rx_clk_en),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nor2_1 _314_ (
    .A(\u_rx.state[2] ),
    .B(\u_rx.state[0] ),
    .Y(_099_)
  );
  sky130_fd_sc_hd__or3_1 _315_ (
    .A(\u_rx.state[2] ),
    .B(\u_rx.state[0] ),
    .C(\u_rx.state[1] ),
    .X(_100_)
  );
  sky130_fd_sc_hd__a21boi_0 _316_ (
    .A1(_085_),
    .A2(_099_),
    .B1_N(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__a21oi_1 _317_ (
    .A1(_078_),
    .A2(_101_),
    .B1(_098_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a41oi_1 _318_ (
    .A1(\u_rx.sample[0] ),
    .A2(\u_rx.sample[1] ),
    .A3(\u_rx.sample[2] ),
    .A4(rx_clk_en),
    .B1(\u_rx.sample[3] ),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nor3_1 _319_ (
    .A(rst),
    .B(_102_),
    .C(_103_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__a21oi_1 _320_ (
    .A1(\u_rx.state[0] ),
    .A2(_078_),
    .B1(_099_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__o211a_1 _321_ (
    .A1(_071_),
    .A2(_085_),
    .B1(_104_),
    .C1(rx_clk_en),
    .X(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _322_ (
    .A(\u_rx.index[0] ),
    .B(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand3_1 _323_ (
    .A(\u_rx.index[0] ),
    .B(\u_rx.index[1] ),
    .C(_105_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand4_1 _324_ (
    .A(\u_rx.index[0] ),
    .B(\u_rx.index[1] ),
    .C(\u_rx.index[2] ),
    .D(_105_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a21o_1 _325_ (
    .A1(_071_),
    .A2(_105_),
    .B1(rst),
    .X(_109_)
  );
  sky130_fd_sc_hd__xor2_1 _326_ (
    .A(\u_rx.index[3] ),
    .B(_108_),
    .X(_110_)
  );
  sky130_fd_sc_hd__nor2_1 _327_ (
    .A(_109_),
    .B(_110_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _328_ (
    .A(_071_),
    .B(_086_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nand3_1 _329_ (
    .A(\u_rx.state[2] ),
    .B(rx_clk_en),
    .C(_085_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand2_1 _330_ (
    .A(\u_rx.rx_s ),
    .B(_111_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand2_1 _331_ (
    .A(\u_rx.temp[7] ),
    .B(_112_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__a21oi_1 _332_ (
    .A1(_113_),
    .A2(_114_),
    .B1(rst),
    .Y(_007_)
  );
  sky130_fd_sc_hd__or2_0 _333_ (
    .A(rst),
    .B(\u_rx.rx_sync[0] ),
    .X(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _334_ (
    .A(\u_rx.temp[1] ),
    .B(_087_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nand2_1 _335_ (
    .A(data_out[1]),
    .B(_088_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a21oi_1 _336_ (
    .A1(_115_),
    .A2(_116_),
    .B1(rst),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _337_ (
    .A(\u_rx.temp[0] ),
    .B(_087_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand2_1 _338_ (
    .A(data_out[0]),
    .B(_088_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__a21oi_1 _339_ (
    .A1(_117_),
    .A2(_118_),
    .B1(rst),
    .Y(_010_)
  );
  sky130_fd_sc_hd__xnor2_1 _340_ (
    .A(baud_sel[2]),
    .B(\u_baud.sel_q[2] ),
    .Y(_119_)
  );
  sky130_fd_sc_hd__xnor2_1 _341_ (
    .A(baud_sel[0]),
    .B(\u_baud.sel_q[0] ),
    .Y(_120_)
  );
  sky130_fd_sc_hd__xor2_1 _342_ (
    .A(baud_sel[1]),
    .B(\u_baud.sel_q[1] ),
    .X(_121_)
  );
  sky130_fd_sc_hd__nor2_1 _343_ (
    .A(rst),
    .B(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__and3_1 _344_ (
    .A(_119_),
    .B(_120_),
    .C(_122_),
    .X(_123_)
  );
  sky130_fd_sc_hd__nand3_1 _345_ (
    .A(_119_),
    .B(_120_),
    .C(_122_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nor2b_1 _346_ (
    .A(baud_sel[2]),
    .B_N(baud_sel[0]),
    .Y(_125_)
  );
  sky130_fd_sc_hd__or3b_1 _347_ (
    .A(baud_sel[2]),
    .B(baud_sel[1]),
    .C_N(baud_sel[0]),
    .X(_126_)
  );
  sky130_fd_sc_hd__or3b_1 _348_ (
    .A(baud_sel[0]),
    .B(baud_sel[1]),
    .C_N(baud_sel[2]),
    .X(_127_)
  );
  sky130_fd_sc_hd__nand2b_1 _349_ (
    .A_N(baud_sel[2]),
    .B(baud_sel[1]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nand3_1 _350_ (
    .A(_126_),
    .B(_127_),
    .C(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand3b_1 _351_ (
    .A_N(baud_sel[2]),
    .B(baud_sel[1]),
    .C(baud_sel[0]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nand2_1 _352_ (
    .A(\u_baud.counter_tx[7] ),
    .B(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__a41oi_1 _353_ (
    .A1(\u_baud.counter_tx[1] ),
    .A2(\u_baud.counter_tx[0] ),
    .A3(_129_),
    .A4(_131_),
    .B1(\u_baud.counter_tx[13] ),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nor3b_1 _354_ (
    .A(baud_sel[0]),
    .B(baud_sel[2]),
    .C_N(baud_sel[1]),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a31oi_1 _355_ (
    .A1(_126_),
    .A2(_127_),
    .A3(_128_),
    .B1(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__or3_1 _356_ (
    .A(\u_baud.counter_tx[1] ),
    .B(\u_baud.counter_tx[0] ),
    .C(_129_),
    .X(_135_)
  );
  sky130_fd_sc_hd__a221o_1 _357_ (
    .A1(_073_),
    .A2(_134_),
    .B1(_135_),
    .B2(\u_baud.counter_tx[13] ),
    .C1(_132_),
    .X(_136_)
  );
  sky130_fd_sc_hd__nand2b_1 _358_ (
    .A_N(\u_baud.counter_tx[9] ),
    .B(\u_baud.counter_tx[4] ),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nor2b_1 _359_ (
    .A(\u_baud.counter_tx[4] ),
    .B_N(\u_baud.counter_tx[9] ),
    .Y(_138_)
  );
  sky130_fd_sc_hd__a21oi_1 _360_ (
    .A1(_127_),
    .A2(_128_),
    .B1(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nor3b_1 _361_ (
    .A(\u_baud.counter_tx[2] ),
    .B(\u_baud.counter_tx[10] ),
    .C_N(\u_baud.counter_tx[5] ),
    .Y(_140_)
  );
  sky130_fd_sc_hd__and3b_1 _362_ (
    .A_N(\u_baud.counter_tx[5] ),
    .B(\u_baud.counter_tx[10] ),
    .C(\u_baud.counter_tx[2] ),
    .X(_141_)
  );
  sky130_fd_sc_hd__mux2i_1 _363_ (
    .A0(_140_),
    .A1(_141_),
    .S(_125_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a311oi_1 _364_ (
    .A1(_127_),
    .A2(_128_),
    .A3(_137_),
    .B1(_139_),
    .C1(_142_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nand2_1 _365_ (
    .A(\u_baud.counter_tx[6] ),
    .B(\u_baud.counter_tx[11] ),
    .Y(_144_)
  );
  sky130_fd_sc_hd__o21ai_0 _366_ (
    .A1(\u_baud.counter_tx[12] ),
    .A2(_126_),
    .B1(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__xnor2_1 _367_ (
    .A(\u_baud.counter_tx[8] ),
    .B(_127_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__xor2_1 _368_ (
    .A(\u_baud.counter_tx[3] ),
    .B(_133_),
    .X(_147_)
  );
  sky130_fd_sc_hd__a2111oi_0 _369_ (
    .A1(\u_baud.counter_tx[12] ),
    .A2(_126_),
    .B1(_145_),
    .C1(_146_),
    .D1(_147_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a21o_1 _370_ (
    .A1(_129_),
    .A2(_130_),
    .B1(\u_baud.counter_tx[7] ),
    .X(_149_)
  );
  sky130_fd_sc_hd__o2111ai_1 _371_ (
    .A1(\u_baud.counter_tx[11] ),
    .A2(_134_),
    .B1(_143_),
    .C1(_148_),
    .D1(_149_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__o21ai_0 _372_ (
    .A1(_136_),
    .A2(_150_),
    .B1(_123_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__and3_1 _373_ (
    .A(\u_baud.counter_tx[1] ),
    .B(\u_baud.counter_tx[0] ),
    .C(\u_baud.counter_tx[2] ),
    .X(_152_)
  );
  sky130_fd_sc_hd__and4_1 _374_ (
    .A(\u_baud.counter_tx[1] ),
    .B(\u_baud.counter_tx[0] ),
    .C(\u_baud.counter_tx[2] ),
    .D(\u_baud.counter_tx[3] ),
    .X(_153_)
  );
  sky130_fd_sc_hd__and2_0 _375_ (
    .A(\u_baud.counter_tx[4] ),
    .B(_153_),
    .X(_154_)
  );
  sky130_fd_sc_hd__and4_1 _376_ (
    .A(\u_baud.counter_tx[4] ),
    .B(\u_baud.counter_tx[5] ),
    .C(\u_baud.counter_tx[6] ),
    .D(_153_),
    .X(_155_)
  );
  sky130_fd_sc_hd__and2_0 _377_ (
    .A(\u_baud.counter_tx[7] ),
    .B(_155_),
    .X(_156_)
  );
  sky130_fd_sc_hd__a21oi_1 _378_ (
    .A1(\u_baud.counter_tx[8] ),
    .A2(_156_),
    .B1(\u_baud.counter_tx[9] ),
    .Y(_157_)
  );
  sky130_fd_sc_hd__and4_1 _379_ (
    .A(\u_baud.counter_tx[7] ),
    .B(\u_baud.counter_tx[8] ),
    .C(\u_baud.counter_tx[9] ),
    .D(_155_),
    .X(_158_)
  );
  sky130_fd_sc_hd__nor3_1 _380_ (
    .A(_151_),
    .B(_157_),
    .C(_158_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__and2_0 _381_ (
    .A(wr_en),
    .B(_076_),
    .X(_159_)
  );
  sky130_fd_sc_hd__nand2_1 _382_ (
    .A(wr_en),
    .B(_076_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a311oi_1 _383_ (
    .A1(\u_tx.bitpos[2] ),
    .A2(\u_tx.bitpos[0] ),
    .A3(\u_tx.bitpos[1] ),
    .B1(_070_),
    .C1(\u_tx.state[0] ),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nand2_1 _384_ (
    .A(tx_clk_en),
    .B(_161_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nand2_1 _385_ (
    .A(_160_),
    .B(_162_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__xnor2_1 _386_ (
    .A(\u_tx.bitpos[0] ),
    .B(\u_tx.bitpos[1] ),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nor2_1 _387_ (
    .A(_162_),
    .B(_164_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__a31oi_1 _388_ (
    .A1(\u_tx.bitpos[1] ),
    .A2(_160_),
    .A3(_162_),
    .B1(_165_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nor2_1 _389_ (
    .A(rst),
    .B(_166_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__a21oi_1 _390_ (
    .A1(tx_clk_en),
    .A2(_161_),
    .B1(\u_tx.bitpos[0] ),
    .Y(_167_)
  );
  sky130_fd_sc_hd__a211oi_1 _391_ (
    .A1(\u_tx.bitpos[0] ),
    .A2(_163_),
    .B1(_167_),
    .C1(rst),
    .Y(_013_)
  );
  sky130_fd_sc_hd__xnor2_1 _392_ (
    .A(\u_baud.counter_tx[8] ),
    .B(_156_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nor2_1 _393_ (
    .A(_151_),
    .B(_168_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xnor2_1 _394_ (
    .A(\u_baud.counter_tx[7] ),
    .B(_155_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nor2_1 _395_ (
    .A(_151_),
    .B(_169_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__a21oi_1 _396_ (
    .A1(\u_baud.counter_tx[5] ),
    .A2(_154_),
    .B1(\u_baud.counter_tx[6] ),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nor3_1 _397_ (
    .A(_151_),
    .B(_155_),
    .C(_170_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__xnor2_1 _398_ (
    .A(\u_baud.counter_tx[5] ),
    .B(_154_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nor2_1 _399_ (
    .A(_151_),
    .B(_171_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nor2_1 _400_ (
    .A(\u_baud.counter_tx[4] ),
    .B(_153_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nor3_1 _401_ (
    .A(_151_),
    .B(_154_),
    .C(_172_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nor2_1 _402_ (
    .A(\u_baud.counter_tx[3] ),
    .B(_152_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__nor3_1 _403_ (
    .A(_151_),
    .B(_153_),
    .C(_173_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__a21oi_1 _404_ (
    .A1(\u_baud.counter_tx[1] ),
    .A2(\u_baud.counter_tx[0] ),
    .B1(\u_baud.counter_tx[2] ),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nor3_1 _405_ (
    .A(_151_),
    .B(_152_),
    .C(_174_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__xnor2_1 _406_ (
    .A(\u_baud.counter_tx[1] ),
    .B(\u_baud.counter_tx[0] ),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nor2_1 _407_ (
    .A(_151_),
    .B(_175_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _408_ (
    .A(data_in[6]),
    .B(_159_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__nand2_1 _409_ (
    .A(\u_tx.data[6] ),
    .B(_160_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__a21oi_1 _410_ (
    .A1(_176_),
    .A2(_177_),
    .B1(rst),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _411_ (
    .A(data_in[5]),
    .B(_159_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nand2_1 _412_ (
    .A(\u_tx.data[5] ),
    .B(_160_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__a21oi_1 _413_ (
    .A1(_178_),
    .A2(_179_),
    .B1(rst),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _414_ (
    .A(data_in[4]),
    .B(_159_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nand2_1 _415_ (
    .A(\u_tx.data[4] ),
    .B(_160_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__a21oi_1 _416_ (
    .A1(_180_),
    .A2(_181_),
    .B1(rst),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _417_ (
    .A(data_in[3]),
    .B(_159_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__nand2_1 _418_ (
    .A(\u_tx.data[3] ),
    .B(_160_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__a21oi_1 _419_ (
    .A1(_182_),
    .A2(_183_),
    .B1(rst),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _420_ (
    .A(data_in[2]),
    .B(_159_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__nand2_1 _421_ (
    .A(\u_tx.data[2] ),
    .B(_160_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__a21oi_1 _422_ (
    .A1(_184_),
    .A2(_185_),
    .B1(rst),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand2_1 _423_ (
    .A(data_in[1]),
    .B(_159_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__nand2_1 _424_ (
    .A(\u_tx.data[1] ),
    .B(_160_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__a21oi_1 _425_ (
    .A1(_186_),
    .A2(_187_),
    .B1(rst),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _426_ (
    .A(data_in[0]),
    .B(_159_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nand2_1 _427_ (
    .A(\u_tx.data[0] ),
    .B(_160_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__a21oi_1 _428_ (
    .A1(_188_),
    .A2(_189_),
    .B1(rst),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nor2_1 _429_ (
    .A(\u_baud.counter_tx[0] ),
    .B(_151_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nor4b_1 _430_ (
    .A(\u_baud.counter_rx[2] ),
    .B(_074_),
    .C(_134_),
    .D_N(\u_baud.counter_rx[1] ),
    .Y(_190_)
  );
  sky130_fd_sc_hd__nor3b_1 _431_ (
    .A(\u_baud.counter_rx[1] ),
    .B(\u_baud.counter_rx[7] ),
    .C_N(\u_baud.counter_rx[2] ),
    .Y(_191_)
  );
  sky130_fd_sc_hd__a21oi_1 _432_ (
    .A1(_134_),
    .A2(_191_),
    .B1(_190_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__a21oi_1 _433_ (
    .A1(_129_),
    .A2(_130_),
    .B1(\u_baud.counter_rx[3] ),
    .Y(_193_)
  );
  sky130_fd_sc_hd__a21oi_1 _434_ (
    .A1(_127_),
    .A2(_128_),
    .B1(\u_baud.counter_rx[5] ),
    .Y(_194_)
  );
  sky130_fd_sc_hd__o21ai_0 _435_ (
    .A1(_072_),
    .A2(_127_),
    .B1(\u_baud.counter_rx[4] ),
    .Y(_195_)
  );
  sky130_fd_sc_hd__nor2b_1 _436_ (
    .A(_194_),
    .B_N(_195_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__nor2_1 _437_ (
    .A(\u_baud.counter_rx[4] ),
    .B(_127_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__xor2_1 _438_ (
    .A(\u_baud.counter_rx[6] ),
    .B(_125_),
    .X(_198_)
  );
  sky130_fd_sc_hd__a311oi_1 _439_ (
    .A1(\u_baud.counter_rx[5] ),
    .A2(_127_),
    .A3(_128_),
    .B1(_197_),
    .C1(_198_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__nor2b_1 _440_ (
    .A(\u_baud.counter_rx[4] ),
    .B_N(\u_baud.counter_rx[0] ),
    .Y(_200_)
  );
  sky130_fd_sc_hd__o21ai_0 _441_ (
    .A1(\u_baud.counter_rx[8] ),
    .A2(_200_),
    .B1(_126_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nand2_1 _442_ (
    .A(\u_baud.counter_rx[3] ),
    .B(_130_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__a21o_1 _443_ (
    .A1(\u_baud.counter_rx[0] ),
    .A2(\u_baud.counter_rx[8] ),
    .B1(_126_),
    .X(_203_)
  );
  sky130_fd_sc_hd__o211a_1 _444_ (
    .A1(\u_baud.counter_rx[9] ),
    .A2(_202_),
    .B1(_203_),
    .C1(_201_),
    .X(_204_)
  );
  sky130_fd_sc_hd__nand2_1 _445_ (
    .A(\u_baud.counter_rx[9] ),
    .B(_129_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__nand4_1 _446_ (
    .A(_196_),
    .B(_199_),
    .C(_204_),
    .D(_205_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__o31ai_1 _447_ (
    .A1(_192_),
    .A2(_193_),
    .A3(_206_),
    .B1(_123_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__and3_1 _448_ (
    .A(\u_baud.counter_rx[1] ),
    .B(\u_baud.counter_rx[0] ),
    .C(\u_baud.counter_rx[2] ),
    .X(_208_)
  );
  sky130_fd_sc_hd__and4_1 _449_ (
    .A(\u_baud.counter_rx[1] ),
    .B(\u_baud.counter_rx[0] ),
    .C(\u_baud.counter_rx[2] ),
    .D(\u_baud.counter_rx[3] ),
    .X(_209_)
  );
  sky130_fd_sc_hd__and2_0 _450_ (
    .A(\u_baud.counter_rx[4] ),
    .B(_209_),
    .X(_210_)
  );
  sky130_fd_sc_hd__nand4_1 _451_ (
    .A(\u_baud.counter_rx[4] ),
    .B(\u_baud.counter_rx[5] ),
    .C(\u_baud.counter_rx[6] ),
    .D(_209_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nor2_1 _452_ (
    .A(_074_),
    .B(_211_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__nor2_1 _453_ (
    .A(\u_baud.counter_rx[8] ),
    .B(_212_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nand2_1 _454_ (
    .A(\u_baud.counter_rx[8] ),
    .B(_212_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__nor3b_1 _455_ (
    .A(_207_),
    .B(_213_),
    .C_N(_214_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__xnor2_1 _456_ (
    .A(_074_),
    .B(_211_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__nor2_1 _457_ (
    .A(_207_),
    .B(_215_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a21oi_1 _458_ (
    .A1(\u_baud.counter_rx[5] ),
    .A2(_210_),
    .B1(\u_baud.counter_rx[6] ),
    .Y(_216_)
  );
  sky130_fd_sc_hd__nor3b_1 _459_ (
    .A(_216_),
    .B(_207_),
    .C_N(_211_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__xnor2_1 _460_ (
    .A(\u_baud.counter_rx[5] ),
    .B(_210_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__nor2_1 _461_ (
    .A(_207_),
    .B(_217_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nor2_1 _462_ (
    .A(\u_baud.counter_rx[4] ),
    .B(_209_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__nor3_1 _463_ (
    .A(_207_),
    .B(_210_),
    .C(_218_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor2_1 _464_ (
    .A(\u_baud.counter_rx[3] ),
    .B(_208_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__nor3_1 _465_ (
    .A(_207_),
    .B(_209_),
    .C(_219_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__or2_0 _466_ (
    .A(tx_line),
    .B(rst),
    .X(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _467_ (
    .A(\u_rx.temp[7] ),
    .B(_111_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__nand2_1 _468_ (
    .A(\u_rx.temp[6] ),
    .B(_112_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__a21oi_1 _469_ (
    .A1(_220_),
    .A2(_221_),
    .B1(rst),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _470_ (
    .A(\u_rx.temp[6] ),
    .B(_111_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__nand2_1 _471_ (
    .A(\u_rx.temp[5] ),
    .B(_112_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__a21oi_1 _472_ (
    .A1(_222_),
    .A2(_223_),
    .B1(rst),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nand2_1 _473_ (
    .A(\u_rx.temp[5] ),
    .B(_111_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__nand2_1 _474_ (
    .A(\u_rx.temp[4] ),
    .B(_112_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__a21oi_1 _475_ (
    .A1(_224_),
    .A2(_225_),
    .B1(rst),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _476_ (
    .A(\u_rx.temp[4] ),
    .B(_111_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__nand2_1 _477_ (
    .A(\u_rx.temp[3] ),
    .B(_112_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__a21oi_1 _478_ (
    .A1(_226_),
    .A2(_227_),
    .B1(rst),
    .Y(_040_)
  );
  sky130_fd_sc_hd__mux4_2 _479_ (
    .A0(\u_tx.data[0] ),
    .A1(\u_tx.data[1] ),
    .A2(\u_tx.data[4] ),
    .A3(\u_tx.data[5] ),
    .S0(\u_tx.bitpos[0] ),
    .S1(\u_tx.bitpos[2] ),
    .X(_228_)
  );
  sky130_fd_sc_hd__clkinv_1 _480_ (
    .A(_228_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__mux4_2 _481_ (
    .A0(\u_tx.data[2] ),
    .A1(\u_tx.data[3] ),
    .A2(\u_tx.data[6] ),
    .A3(\u_tx.data[7] ),
    .S0(\u_tx.bitpos[0] ),
    .S1(\u_tx.bitpos[2] ),
    .X(_230_)
  );
  sky130_fd_sc_hd__a21oi_1 _482_ (
    .A1(\u_tx.bitpos[1] ),
    .A2(_230_),
    .B1(\u_tx.state[0] ),
    .Y(_231_)
  );
  sky130_fd_sc_hd__o21ai_0 _483_ (
    .A1(\u_tx.bitpos[1] ),
    .A2(_229_),
    .B1(_231_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__nand3_1 _484_ (
    .A(\u_tx.state[1] ),
    .B(tx_clk_en),
    .C(_232_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__nand2_1 _485_ (
    .A(tx_clk_en),
    .B(busy),
    .Y(_234_)
  );
  sky130_fd_sc_hd__a21oi_1 _486_ (
    .A1(tx_line),
    .A2(_234_),
    .B1(rst),
    .Y(_235_)
  );
  sky130_fd_sc_hd__nand2_1 _487_ (
    .A(_233_),
    .B(_235_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand2_1 _488_ (
    .A(data_in[7]),
    .B(_159_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__nand2_1 _489_ (
    .A(\u_tx.data[7] ),
    .B(_160_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__a21oi_1 _490_ (
    .A1(_236_),
    .A2(_237_),
    .B1(rst),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a31oi_1 _491_ (
    .A1(\u_tx.bitpos[0] ),
    .A2(\u_tx.bitpos[1] ),
    .A3(_163_),
    .B1(\u_tx.bitpos[2] ),
    .Y(_238_)
  );
  sky130_fd_sc_hd__nor3_1 _492_ (
    .A(rst),
    .B(_159_),
    .C(_238_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _493_ (
    .A(_160_),
    .B(_234_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__a21oi_1 _494_ (
    .A1(\u_tx.state[0] ),
    .A2(tx_clk_en),
    .B1(\u_tx.state[1] ),
    .Y(_240_)
  );
  sky130_fd_sc_hd__and3_1 _495_ (
    .A(\u_tx.state[0] ),
    .B(\u_tx.state[1] ),
    .C(tx_clk_en),
    .X(_241_)
  );
  sky130_fd_sc_hd__nor3_1 _496_ (
    .A(rst),
    .B(_240_),
    .C(_241_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _497_ (
    .A(\u_rx.temp[3] ),
    .B(_111_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__nand2_1 _498_ (
    .A(\u_rx.temp[2] ),
    .B(_112_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__a21oi_1 _499_ (
    .A1(_242_),
    .A2(_243_),
    .B1(rst),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _500_ (
    .A(\u_rx.temp[2] ),
    .B(_111_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__nand2_1 _501_ (
    .A(\u_rx.temp[1] ),
    .B(_112_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__a21oi_1 _502_ (
    .A1(_244_),
    .A2(_245_),
    .B1(rst),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _503_ (
    .A(\u_rx.temp[1] ),
    .B(_111_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__nand2_1 _504_ (
    .A(\u_rx.temp[0] ),
    .B(_112_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__a21oi_1 _505_ (
    .A1(_246_),
    .A2(_247_),
    .B1(rst),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a21oi_1 _506_ (
    .A1(\u_baud.counter_rx[1] ),
    .A2(\u_baud.counter_rx[0] ),
    .B1(\u_baud.counter_rx[2] ),
    .Y(_248_)
  );
  sky130_fd_sc_hd__nor3_1 _507_ (
    .A(_207_),
    .B(_208_),
    .C(_248_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__xor2_1 _508_ (
    .A(\u_rx.index[2] ),
    .B(_107_),
    .X(_249_)
  );
  sky130_fd_sc_hd__nor2_1 _509_ (
    .A(_109_),
    .B(_249_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__a21oi_1 _510_ (
    .A1(\u_rx.index[0] ),
    .A2(_105_),
    .B1(\u_rx.index[1] ),
    .Y(_250_)
  );
  sky130_fd_sc_hd__nor3b_1 _511_ (
    .A(_109_),
    .B(_250_),
    .C_N(_107_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor2_1 _512_ (
    .A(\u_rx.index[0] ),
    .B(_105_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__nor3b_1 _513_ (
    .A(_109_),
    .B(_251_),
    .C_N(_106_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__xnor2_1 _514_ (
    .A(\u_baud.counter_rx[1] ),
    .B(\u_baud.counter_rx[0] ),
    .Y(_252_)
  );
  sky130_fd_sc_hd__nor2_1 _515_ (
    .A(_207_),
    .B(_252_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nor2_1 _516_ (
    .A(\u_baud.counter_rx[0] ),
    .B(_207_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _517_ (
    .A(\u_tx.state[0] ),
    .B(_239_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__a2111oi_0 _518_ (
    .A1(\u_tx.state[0] ),
    .A2(tx_clk_en),
    .B1(_161_),
    .C1(_253_),
    .D1(rst),
    .Y(_054_)
  );
  sky130_fd_sc_hd__a31oi_1 _519_ (
    .A1(\u_rx.sample[0] ),
    .A2(\u_rx.sample[1] ),
    .A3(rx_clk_en),
    .B1(\u_rx.sample[2] ),
    .Y(_254_)
  );
  sky130_fd_sc_hd__a21oi_1 _520_ (
    .A1(_077_),
    .A2(_100_),
    .B1(_098_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__nor3_1 _521_ (
    .A(rst),
    .B(_254_),
    .C(_255_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nor2_1 _522_ (
    .A(\u_rx.sample[1] ),
    .B(_097_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__o21ai_0 _523_ (
    .A1(\u_rx.sample[0] ),
    .A2(\u_rx.sample[1] ),
    .B1(_100_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__a21oi_1 _524_ (
    .A1(\u_rx.sample[0] ),
    .A2(\u_rx.sample[1] ),
    .B1(_257_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__nor2_1 _525_ (
    .A(_098_),
    .B(_258_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__nor3_1 _526_ (
    .A(rst),
    .B(_256_),
    .C(_259_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__a21oi_1 _527_ (
    .A1(_097_),
    .A2(_101_),
    .B1(\u_rx.sample[0] ),
    .Y(_260_)
  );
  sky130_fd_sc_hd__a211oi_1 _528_ (
    .A1(\u_rx.sample[0] ),
    .A2(rx_clk_en),
    .B1(_260_),
    .C1(rst),
    .Y(_057_)
  );
  sky130_fd_sc_hd__and2_0 _529_ (
    .A(\u_baud.counter_tx[10] ),
    .B(_158_),
    .X(_261_)
  );
  sky130_fd_sc_hd__and3_1 _530_ (
    .A(\u_baud.counter_tx[10] ),
    .B(\u_baud.counter_tx[11] ),
    .C(_158_),
    .X(_262_)
  );
  sky130_fd_sc_hd__nand4_1 _531_ (
    .A(\u_baud.counter_tx[10] ),
    .B(\u_baud.counter_tx[11] ),
    .C(\u_baud.counter_tx[12] ),
    .D(_158_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__nor2_1 _532_ (
    .A(\u_baud.counter_tx[12] ),
    .B(_262_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__nor3b_1 _533_ (
    .A(_264_),
    .B(_151_),
    .C_N(_263_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor2_1 _534_ (
    .A(\u_baud.counter_tx[11] ),
    .B(_261_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__nor3_1 _535_ (
    .A(_151_),
    .B(_262_),
    .C(_265_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor2_1 _536_ (
    .A(\u_baud.counter_tx[10] ),
    .B(_158_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__nor3_1 _537_ (
    .A(_151_),
    .B(_261_),
    .C(_266_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _538_ (
    .A(\u_rx.temp[6] ),
    .B(_087_),
    .Y(_267_)
  );
  sky130_fd_sc_hd__nand2_1 _539_ (
    .A(data_out[6]),
    .B(_088_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__a21oi_1 _540_ (
    .A1(_267_),
    .A2(_268_),
    .B1(rst),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _541_ (
    .A(\u_rx.temp[5] ),
    .B(_087_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__nand2_1 _542_ (
    .A(data_out[5]),
    .B(_088_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__a21oi_1 _543_ (
    .A1(_269_),
    .A2(_270_),
    .B1(rst),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nor4_1 _544_ (
    .A(_124_),
    .B(_192_),
    .C(_193_),
    .D(_206_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__xor2_1 _545_ (
    .A(\u_baud.counter_rx[9] ),
    .B(_214_),
    .X(_271_)
  );
  sky130_fd_sc_hd__nor2_1 _546_ (
    .A(_207_),
    .B(_271_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor3_1 _547_ (
    .A(_124_),
    .B(_136_),
    .C(_150_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__xor2_1 _548_ (
    .A(\u_baud.counter_tx[13] ),
    .B(_263_),
    .X(_272_)
  );
  sky130_fd_sc_hd__nor2_1 _549_ (
    .A(_151_),
    .B(_272_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _550_ (
    .A(\u_rx.temp[4] ),
    .B(_087_),
    .Y(_273_)
  );
  sky130_fd_sc_hd__nand2_1 _551_ (
    .A(data_out[4]),
    .B(_088_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__a21oi_1 _552_ (
    .A1(_273_),
    .A2(_274_),
    .B1(rst),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _553_ (
    .A(\u_rx.temp[3] ),
    .B(_087_),
    .Y(_275_)
  );
  sky130_fd_sc_hd__nand2_1 _554_ (
    .A(data_out[3]),
    .B(_088_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__a21oi_1 _555_ (
    .A1(_275_),
    .A2(_276_),
    .B1(rst),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _556_ (
    .A(\u_rx.temp[2] ),
    .B(_087_),
    .Y(_277_)
  );
  sky130_fd_sc_hd__nand2_1 _557_ (
    .A(data_out[2]),
    .B(_088_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__a21oi_1 _558_ (
    .A1(_277_),
    .A2(_278_),
    .B1(rst),
    .Y(_069_)
  );
  sky130_fd_sc_hd__dfxtp_1 _559_ (
    .CLK(clk),
    .D(_003_),
    .Q(rdy)
  );
  sky130_fd_sc_hd__dfxtp_1 _560_ (
    .CLK(clk),
    .D(_010_),
    .Q(data_out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _561_ (
    .CLK(clk),
    .D(_009_),
    .Q(data_out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _562_ (
    .CLK(clk),
    .D(_069_),
    .Q(data_out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _563_ (
    .CLK(clk),
    .D(_068_),
    .Q(data_out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _564_ (
    .CLK(clk),
    .D(_067_),
    .Q(data_out[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _565_ (
    .CLK(clk),
    .D(_062_),
    .Q(data_out[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _566_ (
    .CLK(clk),
    .D(_061_),
    .Q(data_out[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _567_ (
    .CLK(clk),
    .D(_004_),
    .Q(data_out[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _568_ (
    .CLK(clk),
    .D(_057_),
    .Q(\u_rx.sample[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _569_ (
    .CLK(clk),
    .D(_056_),
    .Q(\u_rx.sample[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _570_ (
    .CLK(clk),
    .D(_055_),
    .Q(\u_rx.sample[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _571_ (
    .CLK(clk),
    .D(_005_),
    .Q(\u_rx.sample[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _572_ (
    .CLK(clk),
    .D(_051_),
    .Q(\u_rx.index[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _573_ (
    .CLK(clk),
    .D(_050_),
    .Q(\u_rx.index[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _574_ (
    .CLK(clk),
    .D(_049_),
    .Q(\u_rx.index[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _575_ (
    .CLK(clk),
    .D(_006_),
    .Q(\u_rx.index[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _576_ (
    .CLK(clk),
    .D(_047_),
    .Q(\u_rx.temp[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _577_ (
    .CLK(clk),
    .D(_046_),
    .Q(\u_rx.temp[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _578_ (
    .CLK(clk),
    .D(_045_),
    .Q(\u_rx.temp[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _579_ (
    .CLK(clk),
    .D(_040_),
    .Q(\u_rx.temp[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _580_ (
    .CLK(clk),
    .D(_039_),
    .Q(\u_rx.temp[4] )
  );
  sky130_fd_sc_hd__dfxtp_1 _581_ (
    .CLK(clk),
    .D(_038_),
    .Q(\u_rx.temp[5] )
  );
  sky130_fd_sc_hd__dfxtp_1 _582_ (
    .CLK(clk),
    .D(_037_),
    .Q(\u_rx.temp[6] )
  );
  sky130_fd_sc_hd__dfxtp_1 _583_ (
    .CLK(clk),
    .D(_007_),
    .Q(\u_rx.temp[7] )
  );
  sky130_fd_sc_hd__dfxtp_1 _584_ (
    .CLK(clk),
    .D(_036_),
    .Q(\u_rx.rx_sync[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _585_ (
    .CLK(clk),
    .D(_008_),
    .Q(\u_rx.rx_s )
  );
  sky130_fd_sc_hd__dfxtp_1 _586_ (
    .CLK(clk),
    .D(_041_),
    .Q(tx_line)
  );
  sky130_fd_sc_hd__dfxtp_1 _587_ (
    .CLK(clk),
    .D(_028_),
    .Q(\u_tx.data[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _588_ (
    .CLK(clk),
    .D(_027_),
    .Q(\u_tx.data[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _589_ (
    .CLK(clk),
    .D(_026_),
    .Q(\u_tx.data[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _590_ (
    .CLK(clk),
    .D(_025_),
    .Q(\u_tx.data[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _591_ (
    .CLK(clk),
    .D(_024_),
    .Q(\u_tx.data[4] )
  );
  sky130_fd_sc_hd__dfxtp_1 _592_ (
    .CLK(clk),
    .D(_023_),
    .Q(\u_tx.data[5] )
  );
  sky130_fd_sc_hd__dfxtp_1 _593_ (
    .CLK(clk),
    .D(_022_),
    .Q(\u_tx.data[6] )
  );
  sky130_fd_sc_hd__dfxtp_1 _594_ (
    .CLK(clk),
    .D(_042_),
    .Q(\u_tx.data[7] )
  );
  sky130_fd_sc_hd__dfxtp_1 _595_ (
    .CLK(clk),
    .D(_013_),
    .Q(\u_tx.bitpos[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _596_ (
    .CLK(clk),
    .D(_012_),
    .Q(\u_tx.bitpos[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _597_ (
    .CLK(clk),
    .D(_043_),
    .Q(\u_tx.bitpos[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _598_ (
    .CLK(clk),
    .D(_054_),
    .Q(\u_tx.state[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _599_ (
    .CLK(clk),
    .D(_044_),
    .Q(\u_tx.state[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _600_ (
    .CLK(clk),
    .D(_063_),
    .Q(rx_clk_en)
  );
  sky130_fd_sc_hd__dfxtp_1 _601_ (
    .CLK(clk),
    .D(_053_),
    .Q(\u_baud.counter_rx[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _602_ (
    .CLK(clk),
    .D(_052_),
    .Q(\u_baud.counter_rx[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _603_ (
    .CLK(clk),
    .D(_048_),
    .Q(\u_baud.counter_rx[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _604_ (
    .CLK(clk),
    .D(_035_),
    .Q(\u_baud.counter_rx[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _605_ (
    .CLK(clk),
    .D(_034_),
    .Q(\u_baud.counter_rx[4] )
  );
  sky130_fd_sc_hd__dfxtp_1 _606_ (
    .CLK(clk),
    .D(_033_),
    .Q(\u_baud.counter_rx[5] )
  );
  sky130_fd_sc_hd__dfxtp_1 _607_ (
    .CLK(clk),
    .D(_032_),
    .Q(\u_baud.counter_rx[6] )
  );
  sky130_fd_sc_hd__dfxtp_1 _608_ (
    .CLK(clk),
    .D(_031_),
    .Q(\u_baud.counter_rx[7] )
  );
  sky130_fd_sc_hd__dfxtp_1 _609_ (
    .CLK(clk),
    .D(_030_),
    .Q(\u_baud.counter_rx[8] )
  );
  sky130_fd_sc_hd__dfxtp_1 _610_ (
    .CLK(clk),
    .D(_064_),
    .Q(\u_baud.counter_rx[9] )
  );
  sky130_fd_sc_hd__dfxtp_1 _611_ (
    .CLK(clk),
    .D(_065_),
    .Q(tx_clk_en)
  );
  sky130_fd_sc_hd__dfxtp_1 _612_ (
    .CLK(clk),
    .D(_029_),
    .Q(\u_baud.counter_tx[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _613_ (
    .CLK(clk),
    .D(_021_),
    .Q(\u_baud.counter_tx[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _614_ (
    .CLK(clk),
    .D(_020_),
    .Q(\u_baud.counter_tx[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _615_ (
    .CLK(clk),
    .D(_019_),
    .Q(\u_baud.counter_tx[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _616_ (
    .CLK(clk),
    .D(_018_),
    .Q(\u_baud.counter_tx[4] )
  );
  sky130_fd_sc_hd__dfxtp_1 _617_ (
    .CLK(clk),
    .D(_017_),
    .Q(\u_baud.counter_tx[5] )
  );
  sky130_fd_sc_hd__dfxtp_1 _618_ (
    .CLK(clk),
    .D(_016_),
    .Q(\u_baud.counter_tx[6] )
  );
  sky130_fd_sc_hd__dfxtp_1 _619_ (
    .CLK(clk),
    .D(_015_),
    .Q(\u_baud.counter_tx[7] )
  );
  sky130_fd_sc_hd__dfxtp_1 _620_ (
    .CLK(clk),
    .D(_014_),
    .Q(\u_baud.counter_tx[8] )
  );
  sky130_fd_sc_hd__dfxtp_1 _621_ (
    .CLK(clk),
    .D(_011_),
    .Q(\u_baud.counter_tx[9] )
  );
  sky130_fd_sc_hd__dfxtp_1 _622_ (
    .CLK(clk),
    .D(_060_),
    .Q(\u_baud.counter_tx[10] )
  );
  sky130_fd_sc_hd__dfxtp_1 _623_ (
    .CLK(clk),
    .D(_059_),
    .Q(\u_baud.counter_tx[11] )
  );
  sky130_fd_sc_hd__dfxtp_1 _624_ (
    .CLK(clk),
    .D(_058_),
    .Q(\u_baud.counter_tx[12] )
  );
  sky130_fd_sc_hd__dfxtp_1 _625_ (
    .CLK(clk),
    .D(_066_),
    .Q(\u_baud.counter_tx[13] )
  );
  sky130_fd_sc_hd__dfxtp_1 _626_ (
    .CLK(clk),
    .D(_000_),
    .Q(\u_rx.state[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _627_ (
    .CLK(clk),
    .D(_001_),
    .Q(\u_rx.state[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _628_ (
    .CLK(clk),
    .D(_002_),
    .Q(\u_rx.state[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _629_ (
    .CLK(clk),
    .D(baud_sel[0]),
    .Q(\u_baud.sel_q[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _630_ (
    .CLK(clk),
    .D(baud_sel[1]),
    .Q(\u_baud.sel_q[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _631_ (
    .CLK(clk),
    .D(baud_sel[2]),
    .Q(\u_baud.sel_q[2] )
  );
endmodule
